services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/rails/
    ports:
      - "3000:3000"
  jobs:
    command: ["./bin/jobs"]
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/rails/
