@startuml


actor Développeurs as d #LightBlue
actor Gestionnaires as g #LightBlue
rectangle CScope as cs #LightGreen
rectangle GitHub as gh #LightBlue

cs --> gh : Affichage des données de
d --> cs : Consulte 
g --> cs : Consulte
d --> gh : Publie du code sur

legend right
    |Couleur| Type |
    |<#LightGreen>| Système |
    |<#LightBlue>| Entité Externe|
endlegend
@enduml