@startuml PFE_use_case
actor "Développeur" as Dev
actor "Gestionnaire de Projet" as PM
actor "Client" as Client

rectangle {
  Dev --> (Visualiser Historique des Modifications)
  PM --> (Visualiser Historique Fichiers)
  Client --> (Visualiser Contribution)

  (Visualiser Historique des Modifications) .> (Charger Répertoire GitHub) : include
  (Visualiser Historique des Modifications) .> (Sélectionner Fichier) : include

  (Visualiser Historique Fichiers) .> (Charger Répertoire GitHub) : include

  (Visualiser Contribution) .> (Charger Répertoire GitHub) : include
  (Visualiser Contribution) .> (Sélectionner Version) : include
}
@enduml
