@startuml PFE_use_case
actor "Développeur" as Dev
actor "Gestionnaire de Projet" as PM

rectangle {
  (Visualiser Contribution) as VC
  (Visualiser Historique Fichiers) as VHF
  (Visualiser Historique des Modifications) as VHM

  Dev --> VHM
  PM --> VHF
  Dev --> VC
  PM --> VC

  VHM .> (Charger Répertoire GitHub) : include
  VHM ..> (Sélectionner Fichier) : include

  VHF ..> (Charger Répertoire GitHub) : include

  VC ..> (Charger Répertoire GitHub) : include
  VC .> (Sélectionner Version) : include

  VHM -[hidden]right- VC
}
@enduml
