@startuml

left to right direction
skinparam componentStyle rectangle

actor Utilisateur as U
actor "Utilisateur GH" as UGH

database "GitHub Repositories" as GHRepo

rectangle Cscope as CS {
    node "Front-End" as FE {
        component React {
            card "Affichage des données"
            card "Affichage des endpoints"
        }
    }

    node "Back-End" as BE {
        component FastAPI {
            component Router
            component Service
            component PyDriller
        }
    }
}


node GitHub as GH

U --> FE : "Je consulte un repo X dans Cscope"
UGH --> GH : "Je consulte un repo public dans GitHub"
GH --> FE : GitHub application
FE <--> BE : "Requête / Réponse"
PyDriller --> GHRepo : "Récupération des données"
Router --> Service
Service --> PyDriller

note bottom of FE
    Docker container
end note

note bottom of BE
    Docker container
end note

@enduml
