@startuml

skinparam componentStyle rectangle

actor Utilisateur as U
actor "Utilisateur GH" as UGH

database "GitHub Repositories" as GHRepo

rectangle Cscope as CS {
    node "Front-End" as FE {
        component React as react {
            card "Affichage des données"
            card "Affichage des endpoints"
        }
    }

    node "Back-End" as BE {
        component "Ruby on Rails" as ROR
        
    }
}


node GitHub as GH

U -down-> FE : "Je consulte un repo X dans Cscope"
UGH -down-> GH : "Je consulte un repo public dans GitHub"
GH -RIGHT-> FE : << extension navigateur >>
FE <-down-> BE : "Requête / Réponse"
ROR -down-> GHRepo : "Récupération des données"

note right of FE
    Docker container
end note

note bottom of BE
    Docker container
end note

@enduml
