name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  PROJECT_DIR: ./api
jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{env.PROJECT_DIR}}
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
        working-directory: ${{env.PROJECT_DIR}}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{env.PROJECT_DIR}}
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github
        working-directory: ${{env.PROJECT_DIR}}

  test:
    runs-on: ubuntu-latest
    needs: [scan_ruby, lint]  # Ensures this job waits for the previous two jobs
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{env.PROJECT_DIR}}
          bundler-cache: true

      - name: Prepare and run tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bin/rails test
        working-directory: ${{env.PROJECT_DIR}}

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
