name: Docker Image CI

on:
  push:
    branches: [ "docker-compose" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -f ./api/Dockerfile.dev ./api --tag ${{ secrets.DOCKER_USERNAME }}/pfe019-cscope:latest

    - name: Log in to Docker Hub (with Access Token)
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/pfe019-cscope:latest
