@startuml
actor "Client" as Client
participant "Extension" as UI
participant "API Ruby" as API
participant "Dépôt Github" as GR
participant "Base de données" as DB
Client -> UI : Charger le dépôt actuel
UI -> API : Get https://github.com/visevol/Cscope
API -> DB : Vérifier si le dépôt existe
alt Le dépôt existe
    API -> DB : Obtenir les commits
    API -> UI : Retourner les informations des commits
else Le dépôt n'existe pas
    API -> GR : Git clone https://github.com/visevol/Cscope
    GR -> API : 
    API -> DB : Sauvegarder le dépôt
    API -> UI : Retourner les informations des commits
end
UI -> UI : Filtrer les données
UI -> Client : Afficher le graphique
@enduml
